# Generated by Django 4.0.4 on 2022-05-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('choices_call_type', models.CharField(choices=[('gelen', 'gelen'), ('giden', 'giden')], max_length=5)),
            ],
        ),
    ]
