# Generated by Django 4.0.4 on 2022-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_personcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcall',
            name='choices_call_type',
            field=models.CharField(choices=[('gelen', 'gelen'), ('giden', 'giden')], max_length=5, null=True),
        ),
    ]
