# Generated by Django 4.0.4 on 2022-05-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_personcall_choices_call_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcall',
            name='choices_call_type',
            field=models.CharField(choices=[('gelen', 'gelen'), ('giden', 'giden')], max_length=5),
        ),
        migrations.AlterField(
            model_name='personcall',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.person'),
        ),
    ]
