# Generated by Django 4.0.4 on 2022-05-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_personcall_choices_call_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcall',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.person'),
        ),
    ]
