# Generated by Django 4.0.4 on 2022-05-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_personcall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcall',
            name='choices_call_type',
            field=models.CharField(choices=[('gelen', 'gelen'), ('giden', 'giden')], max_length=5, verbose_name='Arama Türü'),
        ),
        migrations.AlterField(
            model_name='personcall',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Açıklma'),
        ),
        migrations.AlterField(
            model_name='personcall',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.person', verbose_name='İsim Soyisim'),
        ),
    ]
