# Generated by Django 4.0.4 on 2022-05-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_personcall_choices_call_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcall',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Açıklma'),
        ),
    ]
