# Generated by Django 4.0.4 on 2022-05-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_personcall_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcall',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.person', verbose_name='İsim Soyisim'),
        ),
    ]
