# Generated by Django 4.0.4 on 2022-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_personcall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
