# Generated by Django 4.0.4 on 2022-05-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_company_company_description_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_description',
            field=models.TextField(max_length=500),
        ),
    ]
