# Generated by Django 4.0.4 on 2022-05-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_alter_company_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_description',
            field=models.TextField(max_length=500, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Firma Adı'),
        ),
    ]
