# Generated by Django 4.0.4 on 2022-05-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_company_company_description_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.company', verbose_name='Firma'),
        ),
    ]
