# Generated by Django 4.0.4 on 2022-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_alter_person_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=150, verbose_name='İsim Soyisim'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Telefon Numarası'),
        ),
    ]
